name: Atualizar Jogos Diariamente

on:
  schedule:
    - cron: '0 11 * * *' # Roda às 08h Brasília todos os dias
  workflow_dispatch: # Botão para rodar manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Versão atualizada para sumir os avisos

      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4 firebase-admin

      - name: Rodar o Robô
        env:
          # Deve ser EXATAMENTE o nome que você salvou no GitHub Secrets
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python bot_jogos.py
